spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/prompt}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:airelawaleria060866}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

prompt:
  auth:
    jwtSecret: 43cnz495jtc83t9n4
    jwtExpirationMs: 900000
    jwtRefreshExpirationMs: 604800000